spring:
  application:
    name: pure-webflux-test
  profiles:
    active: test
  data:
    mongodb:
      uri: mongodb+srv://kute:bailong110@mongo-kute-cluster-9itum.mongodb.net/test?retryWrites=true

server:
  port: 8090
info:
  application: ${spring.application.name}
  version: 0.0.1
  auth: kute



